### ISSUE TITLE
Heimdall v0.2.0 적용

### ISSUE THREAD

**Issue by ghost** [it-chain/bifrost#18]
@junbeomlee 
이전에 말씀하셨던 인증 부분을 컴포넌트 단으로 옮기는것이 저도 좋을 것 같습니다.

그러기 위해서 1)기존 bifrost 코드에서 사용하는 legacy heimdall 코드(?)들을 일단 지금 버전의 heimdall로 변경하고 2)이후에 컴포넌트 단으로 올라갈 기능들을 분류하는 것이 어떨까요?

**Comment by owljoa** [comment]
@junbeomlee 
여기도 조금 봐주세요 ~~ :)

**Comment by ghost** [comment]
@junbeomlee 
사용하는 heimdall 버전은 glide로 바꾸면 되는건가요?
heimdall쪽 태그를 달아야 바꿀수 있겠죠..?

**Comment by junbeomlee** [comment]
heimdall버전은 github에서 바로 바꿀수 있습니다!!

**Comment by junbeomlee** [comment]
heimdall들어가셔서 release버튼 누르면 tag달거나 release설정할 수 있습니다!

**Comment by ghost** [comment]
아 그런것이 아니라.. 제가 로컬에 bifrost 받아서 작업하려 하는데 Vendor에 있는 기존에 사용하던 이전 버전(legacy) heimdall을 지금 버전으로 바꿔서 작업하려고요. (에러가 떠서 눈에 heimdall 사용부분이 눈에 다 보일것 같아서요!)

**Comment by junbeomlee** [comment]
아하!! 그렇게 되면 glide나 dep에서 version을 정해주시면 될 것 같습니다!!

**Comment by junbeomlee** [comment]
heimdall의 현재 tag를 달아주고 glide 혹은 dep으로 현재 tag의 heimdall을 가져오라고 version을 설정해주면 될 것 같습니다!

**Comment by ghost** [comment]
넵 감사합니다~ :)
