### ISSUE TITLE
travis 적용

### ISSUE THREAD

**Issue by junbeomlee** [it-chain/bifrost#19]

**Comment by junbeomlee** [comment]
bifrost가 업그레이드된 heimdall에 맞춰 수정되어야 하므로, 많이 변경되어야 하기 때문에, travis를 통한 자동화 테스트와 포맷팅을 하려고 합니다!

**Comment by ghost** [comment]
헉.. 저 작업 끝나고 올리고 있는데 기다릴까요? 

vendor를 git에서 추적하는것 같아서 https://www.gitignore.io/ 여기서 go, intelij 찾아서 .gitignore 수정하려는데..

 deleted:    ~/key/.keys/929af419c41d59bd5ca06164b5549e6bc3adfe6163239f19aa4cd2e77634b895_rsa4096_pub
        deleted:    ~/key/.keys/fe9ffff46ebe62c748f8cf3bfddb8835eb094fa14e18cf3168ffadd6fad2b257_rsa4096_pri

이 친구들이 따라다니네요;

**Comment by junbeomlee** [comment]
아니요!! 먼저하셔도 됩니다!! 넵

**Comment by ghost** [comment]
@junbeomlee travis ci 적용 권한이 없다고 나오네요..!!
