### ISSUE TITLE
develop 브랜치에서 key, vendor 제거

### ISSUE THREAD

**Issue by ghost** [it-chain/bifrost#25]

**Comment by ghost** [comment]
@junbeomlee 

아래처럼 key가 계속 추적되서 제가 upstream에서 업데이트 받아올수가 없네요 ㅠ
저 경로에 제가 똑같은 파일을 만들어서 지우면 될까요?

![image](https://user-images.githubusercontent.com/32866399/44945453-ba276600-ae24-11e8-8e6d-25fb4227f2d9.png)

**Comment by junbeomlee** [comment]
아니면 develop에서 저것만 지운것을 바로 develop branch에 push하시고 다음 작업 하셔도 될 것 같아요!
