### ISSUE TITLE
지금 travis의 test coverage error 문제 

### ISSUE THREAD

**Issue by ghost** [it-chain/bifrost#30]
@junbeomlee 
지금 cannot use test profile flag with multiple packages 라는 에러가 나고 있는데.. 찾아보니 아래 링크에서

https://groups.google.com/forum/#!topic/golang-nuts/p4WbbnJqTvk

go 1.10 버전에서는 해결됐다고 하네요.

go버전을 업데이트할까요..?
아니면 travis에서 사용할 go 버전만 업데이트 할까요?

**Comment by ghost** [comment]
engine에서 1.10을 사용하신 이유가 이 문제 때문이였나요?

**Comment by junbeomlee** [comment]
1.11은 약간 안정화 안되거같아서 1.10으로 하고있습니다. 항상 최신버전을 따라가고 싶어서 1.11도 시간이 좀 지난후에는 적용 할 수 있을 것 같습니다!! go버전을 1.10으로 업데이트하는것은 찬성입니다!

**Comment by ghost** [comment]
혹.. 그럼 travis환경만이 아니라 사용하시는 go버전이 지금 1.10 사용하고 계신건가요?

**Comment by junbeomlee** [comment]
저는 1.10으로 하고있습니다!!

**Comment by ghost** [comment]
아아 넵! :)
