### ISSUE TITLE
readme에 문제가 있는지.. goveralls 배지가 0%로 뜨네요 ㅠ

### ISSUE THREAD

**Issue by ghost** [it-chain/bifrost#36]
https://coveralls.io/github/it-chain/bifrost 

위 링크에서 보면 59%라고 나오는데..

뭐가 문제일까요

**Comment by junbeomlee** [comment]
저는 59%라고 나옵니다!! 이게 캐쉬나 쿠키가 남아있으면 예전값으로 보여서 그래요!! 나중에 보시면 59로 다시 될꺼에요!

**Comment by ghost** [comment]
아 그러네요! 저도 이제 잘 보이네요 하하;
